using DrivingLessons.Application.Auth;
using DrivingLessons.Application.Common;
using DrivingLessons.Application.Commands.AssignCarToTeacher;
using DrivingLessons.Application.Commands.ChangeCarDetails;
using DrivingLessons.Application.Commands.ChangeMyPassword;
using DrivingLessons.Application.Commands.ChangeStudentDetails;
using DrivingLessons.Application.Commands.ChangeTeacherDetails;
using DrivingLessons.Application.Commands.ChangeUserDetails;
using DrivingLessons.Application.Commands.ChangeUserRole;
using DrivingLessons.Application.Commands.ClosePublication;
using DrivingLessons.Application.Commands.Common;
using DrivingLessons.Application.Commands.CreateCar;
using DrivingLessons.Application.Commands.CreateStudent;
using DrivingLessons.Application.Commands.CreateSubmission;
using DrivingLessons.Application.Commands.CreateTeacher;
using DrivingLessons.Application.Commands.CreateUser;
using DrivingLessons.Application.Commands.CreateWeekSchedule;
using DrivingLessons.Application.Commands.DeactivateStudent;
using DrivingLessons.Application.Commands.DeleteCar;
using DrivingLessons.Application.Commands.DeleteTeacher;
using DrivingLessons.Application.Commands.DeleteUser;
using DrivingLessons.Application.Commands.ExtendPublicationWindow;
using DrivingLessons.Application.Commands.ImportRoster;
using DrivingLessons.Application.Commands.MarkSlotAvailable;
using DrivingLessons.Application.Commands.MarkSlotUnavailable;
using DrivingLessons.Application.Commands.OpenPublication;
using DrivingLessons.Application.Commands.PublishPublication;
using DrivingLessons.Application.Commands.ReactivateStudent;
using DrivingLessons.Application.Commands.ReopenPublication;
using DrivingLessons.Application.Commands.RestoreUser;
using DrivingLessons.Application.Commands.ReviseSubmission;
using DrivingLessons.Application.Commands.SeedFirstAdministrator;
using DrivingLessons.Application.Commands.SetUserTemporaryPassword;
using DrivingLessons.Application.Commands.UnassignCarFromTeacher;
using DrivingLessons.Application.EventHandlers;
using DrivingLessons.Application.Queries.DownloadPublicationExcel;
using DrivingLessons.Application.Queries.FindCars;
using DrivingLessons.Application.Queries.FindPublicationHistory;
using DrivingLessons.Application.Queries.FindStudents;
using DrivingLessons.Application.Queries.FindTeachers;
using DrivingLessons.Application.Queries.FindUsers;
using DrivingLessons.Application.Queries.GetCar;
using DrivingLessons.Application.Queries.GetLatestRosterImport;
using DrivingLessons.Application.Queries.GetMe;
using DrivingLessons.Application.Queries.GetPublication;
using DrivingLessons.Application.Queries.GetPublicationByLink;
using DrivingLessons.Application.Queries.GetPublicationDashboard;
using DrivingLessons.Application.Queries.GetStudent;
using DrivingLessons.Application.Queries.GetTeacher;
using DrivingLessons.Application.Queries.GetUser;
using DrivingLessons.Application.Queries.GetWeekSchedule;
using DrivingLessons.Application.Queries.IdentifyStudent;
using DrivingLessons.Domain.Events;
using Microsoft.Extensions.DependencyInjection;

namespace DrivingLessons.Application;

public static class DependencyInjection
{
    public static IServiceCollection AddApplication(this IServiceCollection services)
    {
        services.AddScoped<LoginInteractor>();
        services.AddScoped<CheckSignedInUserInteractor>();
        services.AddScoped<SeedFirstAdministratorInteractor>();
        services.AddScoped<CreateUserInteractor>();
        services.AddScoped<DeleteUserInteractor>();
        services.AddScoped<RestoreUserInteractor>();
        services.AddScoped<ChangeUserDetailsInteractor>();
        services.AddScoped<ChangeUserRoleInteractor>();
        services.AddScoped<SetUserTemporaryPasswordInteractor>();
        services.AddScoped<ChangeMyPasswordInteractor>();
        services.AddScoped<FindUsersInteractor>();
        services.AddScoped<GetUserInteractor>();
        services.AddScoped<GetMeInteractor>();
        services.AddScoped<CreateTeacherInteractor>();
        services.AddScoped<CreateCarInteractor>();
        services.AddScoped<ChangeTeacherDetailsInteractor>();
        services.AddScoped<ChangeCarDetailsInteractor>();
        services.AddScoped<DeleteTeacherInteractor>();
        services.AddScoped<DeleteCarInteractor>();
        services.AddScoped<AssignCarToTeacherInteractor>();
        services.AddScoped<UnassignCarFromTeacherInteractor>();
        services.AddScoped<GetTeacherInteractor>();
        services.AddScoped<FindTeachersInteractor>();
        services.AddScoped<GetCarInteractor>();
        services.AddScoped<FindCarsInteractor>();
        services.AddScoped<CreateWeekScheduleInteractor>();
        services.AddScoped<MarkSlotUnavailableInteractor>();
        services.AddScoped<MarkSlotAvailableInteractor>();
        services.AddScoped<GetWeekScheduleInteractor>();
        services.AddScoped<PublishPublicationInteractor>();
        services.AddScoped<ExtendPublicationWindowInteractor>();
        services.AddScoped<ReopenPublicationInteractor>();
        services.AddScoped<OpenPublicationInteractor>();
        services.AddScoped<ClosePublicationInteractor>();
        services.AddScoped<GetPublicationInteractor>();
        services.AddScoped<GetPublicationByLinkInteractor>();
        services.AddScoped<GetPublicationDashboardInteractor>();
        services.AddScoped<FindPublicationHistoryInteractor>();
        services.AddScoped<DownloadPublicationExcelInteractor>();
        services.AddScoped<ImportRosterInteractor>();
        services.AddScoped<FindStudentsInteractor>();
        services.AddScoped<CreateStudentInteractor>();
        services.AddScoped<ChangeStudentDetailsInteractor>();
        services.AddScoped<DeactivateStudentInteractor>();
        services.AddScoped<ReactivateStudentInteractor>();
        services.AddScoped<GetStudentInteractor>();
        services.AddScoped<IdentifyStudentInteractor>();
        services.AddScoped<SubmissionContextResolver>();
        services.AddScoped<CreateSubmissionInteractor>();
        services.AddScoped<ReviseSubmissionInteractor>();
        services.AddScoped<GetLatestRosterImportInteractor>();
        services.AddScoped<IDomainEventHandler<WeekScheduleCreated>, WeekScheduleCreatedHandler>();
        services.AddScoped<IDomainEventHandler<PublicationClosed>, PublicationClosedHandler>();
        return services;
    }
}
