// <auto-generated />
using System;
using DrivingLessons.Infrastructure.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DrivingLessons.Infrastructure.EntityFramework.Migrations
{
    [DbContext(typeof(DrivingLessonsDbContext))]
    [Migration("20260713060432_PromoteCarToSharedPool")]
    partial class PromoteCarToSharedPool
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DrivingLessons.Domain.Entities.Car", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Transmission")
                        .HasColumnType("integer")
                        .HasColumnName("transmission");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("cars", (string)null);
                });

            modelBuilder.Entity("DrivingLessons.Domain.Entities.Teacher", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contact_email");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("teachers", (string)null);
                });

            modelBuilder.Entity("DrivingLessons.Domain.Entities.WeekSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid")
                        .HasColumnName("teacher_id");

                    b.Property<DateOnly>("WeekStart")
                        .HasColumnType("date")
                        .HasColumnName("week_start");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId", "WeekStart")
                        .IsUnique();

                    b.ToTable("week_schedules", (string)null);
                });

            modelBuilder.Entity("DrivingLessons.Infrastructure.Auth.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("admin_users", (string)null);
                });

            modelBuilder.Entity("DrivingLessons.Domain.Entities.Car", b =>
                {
                    b.OwnsMany("DrivingLessons.Domain.Entities.TeacherAssignment", "TeacherAssignments", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("TeacherId")
                                .HasColumnType("uuid")
                                .HasColumnName("teacher_id");

                            b1.Property<Guid>("car_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("car_id", "TeacherId")
                                .IsUnique();

                            b1.ToTable("car_teachers", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("car_id");
                        });

                    b.Navigation("TeacherAssignments");
                });

            modelBuilder.Entity("DrivingLessons.Domain.Entities.WeekSchedule", b =>
                {
                    b.OwnsMany("DrivingLessons.Domain.Entities.Slot", "Slots", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("Day")
                                .HasColumnType("integer")
                                .HasColumnName("day");

                            b1.Property<int>("State")
                                .HasColumnType("integer")
                                .HasColumnName("state");

                            b1.Property<int>("Window")
                                .HasColumnType("integer")
                                .HasColumnName("window");

                            b1.Property<Guid>("week_schedule_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("week_schedule_id");

                            b1.ToTable("slots", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("week_schedule_id");
                        });

                    b.Navigation("Slots");
                });
#pragma warning restore 612, 618
        }
    }
}
