// <auto-generated />
using System;
using DrivingLessons.Infrastructure.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DrivingLessons.Infrastructure.EntityFramework.Migrations
{
    [DbContext(typeof(DrivingLessonsDbContext))]
    partial class DrivingLessonsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DrivingLessons.Domain.Entities.Car", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Transmission")
                        .HasColumnType("integer")
                        .HasColumnName("transmission");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("cars", (string)null);
                });

            modelBuilder.Entity("DrivingLessons.Domain.Entities.Publication", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("LinkToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("link_token");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<DateOnly>("WeekStart")
                        .HasColumnType("date")
                        .HasColumnName("week_start");

                    b.HasKey("Id");

                    b.HasIndex("LinkToken")
                        .IsUnique();

                    b.HasIndex("WeekStart")
                        .IsUnique();

                    b.ToTable("publications", (string)null);
                });

            modelBuilder.Entity("DrivingLessons.Domain.Entities.RosterImport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AddedCount")
                        .HasColumnType("integer")
                        .HasColumnName("added_count");

                    b.Property<int>("DeactivatedCount")
                        .HasColumnType("integer")
                        .HasColumnName("deactivated_count");

                    b.Property<int>("FailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_count");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<DateTime>("ImportedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("imported_at_utc");

                    b.Property<int>("UpdatedCount")
                        .HasColumnType("integer")
                        .HasColumnName("updated_count");

                    b.HasKey("Id");

                    b.ToTable("roster_imports", (string)null);
                });

            modelBuilder.Entity("DrivingLessons.Domain.Entities.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<Guid>("CarId")
                        .HasColumnType("uuid")
                        .HasColumnName("car_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LicenseType")
                        .HasColumnType("text")
                        .HasColumnName("license_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("national_id");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid")
                        .HasColumnName("teacher_id");

                    b.HasKey("Id");

                    b.HasIndex("NationalId")
                        .IsUnique();

                    b.ToTable("students", (string)null);
                });

            modelBuilder.Entity("DrivingLessons.Domain.Entities.Teacher", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contact_email");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("teachers", (string)null);
                });

            modelBuilder.Entity("DrivingLessons.Domain.Entities.WeekSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid")
                        .HasColumnName("teacher_id");

                    b.Property<DateOnly>("WeekStart")
                        .HasColumnType("date")
                        .HasColumnName("week_start");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId", "WeekStart")
                        .IsUnique();

                    b.ToTable("week_schedules", (string)null);
                });

            modelBuilder.Entity("DrivingLessons.Infrastructure.Auth.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("admin_users", (string)null);
                });

            modelBuilder.Entity("DrivingLessons.Domain.Entities.Car", b =>
                {
                    b.OwnsMany("DrivingLessons.Domain.Entities.TeacherAssignment", "TeacherAssignments", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("TeacherId")
                                .HasColumnType("uuid")
                                .HasColumnName("teacher_id");

                            b1.Property<Guid>("car_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("car_id", "TeacherId")
                                .IsUnique();

                            b1.ToTable("car_teachers", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("car_id");
                        });

                    b.Navigation("TeacherAssignments");
                });

            modelBuilder.Entity("DrivingLessons.Domain.Entities.Publication", b =>
                {
                    b.OwnsOne("DrivingLessons.Domain.Values.SubmissionWindow", "Window", b1 =>
                        {
                            b1.Property<Guid>("PublicationId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("EndUtc")
                                .HasColumnType("timestamptz")
                                .HasColumnName("window_end_utc");

                            b1.Property<DateTimeOffset>("StartUtc")
                                .HasColumnType("timestamptz")
                                .HasColumnName("window_start_utc");

                            b1.HasKey("PublicationId");

                            b1.ToTable("publications");

                            b1.WithOwner()
                                .HasForeignKey("PublicationId");
                        });

                    b.OwnsMany("DrivingLessons.Domain.Entities.TeacherExcelVersion", "TeacherVersions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("TeacherId")
                                .HasColumnType("uuid")
                                .HasColumnName("teacher_id");

                            b1.Property<int>("Version")
                                .HasColumnType("integer")
                                .HasColumnName("version");

                            b1.Property<Guid>("publication_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("publication_id");

                            b1.ToTable("publication_teacher_versions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("publication_id");
                        });

                    b.Navigation("TeacherVersions");

                    b.Navigation("Window");
                });

            modelBuilder.Entity("DrivingLessons.Domain.Entities.RosterImport", b =>
                {
                    b.OwnsMany("DrivingLessons.Domain.Values.RosterImportEntry", "Entries", b1 =>
                        {
                            b1.Property<int>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("id"));

                            b1.Property<string>("NationalId")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("national_id");

                            b1.Property<int>("Outcome")
                                .HasColumnType("integer")
                                .HasColumnName("outcome");

                            b1.Property<Guid>("roster_import_id")
                                .HasColumnType("uuid");

                            b1.HasKey("id");

                            b1.HasIndex("roster_import_id");

                            b1.ToTable("roster_import_entries", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("roster_import_id");
                        });

                    b.OwnsMany("DrivingLessons.Domain.Values.RosterImportFailure", "Failures", b1 =>
                        {
                            b1.Property<int>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("id"));

                            b1.Property<int>("Reason")
                                .HasColumnType("integer")
                                .HasColumnName("reason");

                            b1.Property<int>("RowNumber")
                                .HasColumnType("integer")
                                .HasColumnName("row_number");

                            b1.Property<string>("StudentName")
                                .HasColumnType("text")
                                .HasColumnName("student_name");

                            b1.Property<Guid>("roster_import_id")
                                .HasColumnType("uuid");

                            b1.HasKey("id");

                            b1.HasIndex("roster_import_id");

                            b1.ToTable("roster_import_failures", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("roster_import_id");
                        });

                    b.Navigation("Entries");

                    b.Navigation("Failures");
                });

            modelBuilder.Entity("DrivingLessons.Domain.Entities.WeekSchedule", b =>
                {
                    b.OwnsMany("DrivingLessons.Domain.Entities.Slot", "Slots", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("Day")
                                .HasColumnType("integer")
                                .HasColumnName("day");

                            b1.Property<int>("State")
                                .HasColumnType("integer")
                                .HasColumnName("state");

                            b1.Property<int>("Window")
                                .HasColumnType("integer")
                                .HasColumnName("window");

                            b1.Property<Guid>("week_schedule_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("week_schedule_id");

                            b1.ToTable("slots", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("week_schedule_id");
                        });

                    b.Navigation("Slots");
                });
#pragma warning restore 612, 618
        }
    }
}
